name: laundry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  accordion: ^2.6.0
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_line: ^3.2.3
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter_google_places_hoc081098: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_widget_from_html_core: ^0.15.2
  fluttertoast: ^8.2.10
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_api_headers: ^4.2.4
  google_maps_flutter: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  http_auth: ^1.0.4
  image_picker: ^1.1.2
  intl: ^0.20.1
  intl_phone_field: ^3.2.0
  lottie: ^3.2.0
  onesignal_flutter: ^5.2.9
  package_info_plus: ^8.1.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  razorpay_flutter: ^1.3.7
  readmore: ^3.0.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  table_calendar: ^3.2.0
  webview_flutter: ^4.10.0
  # google_maps_webservice_ex: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/bottomIcons/
    - assets/trakersIcons/

  fonts:
    - family: Gilroy Black
      fonts:
        - asset: fonts/BasisGrotesqueArabicPro-Black.ttf
    - family: Gilroy Light
      fonts:
        - asset: fonts/BasisGrotesqueArabicPro-Light.ttf
    - family: Gilroy Heavy
      fonts:
        - asset: fonts/Gilroy-Heavy.otf
    - family: Gilroy Medium
      fonts:
        - asset: fonts/BasisGrotesqueArabicPro-Medium.ttf
    - family: Gilroy Bold
      fonts:
        - asset: fonts/BasisGrotesqueArabicPro-Bold.ttf
    - family: Gilroy ExtraBold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
    - family: Gilroy Regular
      fonts:
        - asset: fonts/BasisGrotesqueArabicPro-Regular.ttf
